backend:
  name: Portfolio
  branch: master
  repo: dukemai/Portfolio

media_folder: static/img

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
