backend:
  name: github
  repo: dukemai/Portfolio #replace with your username/repo

media_folder: static/assets

collections:
  - name: settings
    label: Settings
    folder: settings
    create: true
    fields:
      - { name: logo, label: Logo }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }